### ISSUE TITLE
Strange Addon error log when imported

### ISSUE THREAD

**Issue by Spencer87** [Desno365/DesnoGuns-Mod#14]
```
    fireRate: 3,
```

org.mozilla.javascript.EvaluatorException: missing } after property list (cold_war_addon_by_Spencer09.modpkg#582)
    at org.mozilla.javascript.DefaultErrorReporter.runtimeError(Unknown Source)
    at org.mozilla.javascript.DefaultErrorReporter.error(Unknown Source)
    at org.mozilla.javascript.Parser.addError(Unknown Source)
    at org.mozilla.javascript.Parser.reportError(Unknown Source)
    at org.mozilla.javascript.Parser.reportError(Unknown Source)
    at org.mozilla.javascript.Parser.mustMatchToken(Unknown Source)
    at org.mozilla.javascript.Parser.mustMatchToken(Unknown Source)
    at org.mozilla.javascript.Parser.objectLiteral(Unknown Source)
    at org.mozilla.javascript.Parser.primaryExpr(Unknown Source)
    at org.mozilla.javascript.Parser.memberExpr(Unknown Source)
    at org.mozilla.javascript.Parser.unaryExpr(Unknown Source)
    at org.mozilla.javascript.Parser.mulExpr(Unknown Source)
    at org.mozilla.javascript.Parser.addExpr(Unknown Source)
    at org.mozilla.javascript.Parser.shiftExpr(Unknown Source)
    at org.mozilla.javascript.Parser.relExpr(Unknown Source)
    at org.mozilla.javascript.Parser.eqExpr(Unknown Source)
    at org.mozilla.javascript.Parser.bitAndExpr(Unknown Source)
    at org.mozilla.javascript.Parser.bitXorExpr(Unknown Source)
    at org.mozilla.javascript.Parser.bitOrExpr(Unknown Source)
    at org.mozilla.javascript.Parser.andExpr(Unknown Source)
    at org.mozilla.javascript.Parser.orExpr(Unknown Source)
    at org.mozilla.javascript.Parser.condExpr(Unknown Source)
    at org.mozilla.javascript.Parser.assignExpr(Unknown Source)
    at org.mozilla.javascript.Parser.arrayLiteral(Unknown Source)
    at org.mozilla.javascript.Parser.primaryExpr(Unknown Source)
    at org.mozilla.javascript.Parser.memberExpr(Unknown Source)
    at org.mozilla.javascript.Parser.unaryExpr(Unknown Source)
    at org.mozilla.javascript.Parser.mulExpr(Unknown Source)
    at org.mozilla.javascript.Parser.addExpr(Unknown Source)
    at org.mozilla.javascript.Parser.shiftExpr(Unknown Source)
    at org.mozilla.javascript.Parser.relExpr(Unknown Source)
    at org.mozilla.javascript.Parser.eqExpr(Unknown Source)
    at org.mozilla.javascript.Parser.bitAndExpr(Unknown Source)
    at org.mozilla.javascript.Parser.bitXorExpr(Unknown Source)
    at org.mozilla.javascript.Parser.bitOrExpr(Unknown Source)
    at org.mozilla.javascript.Parser.andExpr(Unknown Source)
    at org.mozilla.javascript.Parser.orExpr(Unknown Source)
    at org.mozilla.javascript.Parser.condExpr(Unknown Source)
    at org.mozilla.javascript.Parser.assignExpr(Unknown Source)
    at org.mozilla.javascript.Parser.variables(Unknown Source)
    at org.mozilla.javascript.Parser.statementHelper(Unknown Source)
    at org.mozilla.javascript.Parser.statement(Unknown Source)
    at org.mozilla.javascript.Parser.parse(Unknown Source)
    at org.mozilla.javascript.Parser.parse(Unknown Source)
    at org.mozilla.javascript.Context.compileImpl(Unknown Source)
    at org.mozilla.javascript.Context.compileReader(Unknown Source)
    at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:191)
    at java.lang.Thread.run(Thread.java:818)

**Comment by Desno365** [comment]
You probably forgot a comma or a { somewhere in the code of your addon, as it says the error report it should be near line 582
